name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build

    - name: Create build.tar.gz
      run: |
        tar -czf build.tar.gz -C build .

    - name: Deploy to DigitalOcean Droplet
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DROPLET_IP: ${{ secrets.DROPLET_IP }}
        DROPLET_USER: ${{ secrets.DROPLET_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null build.tar.gz $DROPLET_USER@$DROPLET_IP:/tmp/build.tar.gz
        ssh -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DROPLET_USER@$DROPLET_IP "sudo mkdir -p /var/www/html && sudo tar -xzf /tmp/build.tar.gz -C /var/www/html && sudo rm /tmp/build.tar.gz"
        ssh -i private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DROPLET_USER@$DROPLET_IP "pm2 stop my-app || true && pm2 start"
        rm -f private_key



